### ISSUE TITLE
BQL: trailing dot for sequential statements

### ISSUE THREAD

**Issue by tucnak** [google/badwolf#106]
Semantics the like of `SELECT` and `INSERT` require sequences of statements specific encapsulated in curly bracket. [RDF-related W3 standard](https://www.w3.org/TR/rdf-sparql-query/#GraphPattern) supports trailing dots, and that's a pretty good reason in favour of supporting them here in Badwolf.

However, I vouch to consider dropping dot altogether. After all, they prove little benefit apart from ability to fit multiple statements in a single line; and readability can suffer because of that.

1. Optional trailing dot
2. _Mandatory_ trailing dot
3. No trailing dot at all

These are the available options.

**Comment by rogerlucena** [comment]
Registering updates on this Issue and tracking development:

A deeper search was made about the W3C standard and how other RDF query languages, especially SPARQL, manage trailing dots nowadays.

After testing with the [SPARQL playground](http://sparql-playground.sib.swiss/) and two other online UIs, and looking at the [SPARQL - W3C Recommendation](https://www.w3.org/TR/rdf-sparql-query/), it was noted that with SPARQL the trailing dots are mandatory at the end of each statement, with the exception of the last statement (on which it is optional):

```
SELECT ?name ?mbox
WHERE
  { ?x foaf:name ?name .
    ?x foaf:mbox ?mbox <optional-dot-here> }
```

"Algae" is another RDF Query Language, developed by W3C, that also has trailing dots in all statements with the exception of the last one (as shown [here](https://www.w3.org/2004/05/06-Algae/)).

This way, after some deliberation including Xavier the consensus was to follow this same standard and let BQL just like SPARQL with regards to the trailing dots.

Final guideline: follow the W3C SPARQL recommendation as close as possible. 
In the current Issue #106 it means mandatory trailing dots at the end of each statement with the exception of the last one (on which it will be optional).
