### ISSUE TITLE
Merge efforts with Cayley

### ISSUE THREAD

**Issue by barakmich** [google/badwolf#4]
Hey! I'm the maintainer of the other Google graph project, https://github.com/google/cayley

I know I've been out of the Google-sphere for a year now, but I've still been contributing to Cayley and it's been used in a number of projects and a few production instances. In short, it works pretty well and I'd like to grow it more.

I've read over your repo (you've written in Go too, good choice ;) ). For storage, you've got 99% the same primitives as Cayley. ~~Triples~~ Quads (went down that road, believe me), memory store, indices. Your methods for things like "TriplesForPredicateAndObject" are pretty standard Cayley iterators.

You're doing some nice things with regard to [RDF literals](https://github.com/google/badwolf/blob/master/triple/literal/literal.go) I'd be excited to add to Cayley.

It seems like most of your novel work is in [BQL](https://github.com/google/badwolf/tree/master/bql). I'm just reading up on it now, so I haven't quite gotten the full notion of what makes this a new and interesting query language (would love to discuss), but even proposed as a black box, I'd be happy to add it as a query language in Cayley.

I've always been more of a storage guy, so if your interest is in inference and query languages, that works great. The advantages you'd get would be all sorts of backends, various optimizations on the iterators, while still being able to push forward with your temporal graph idea. Everybody wins. What do you think?

**Comment by barakmich** [comment]
Another option, of course, is to merely use Cayley as a library to fulfill your storage needs -- it's all Go anyway. I'd be happy to PR a https://github.com/google/badwolf/blob/master/storage/storage.go - compatible shim if you'd rather get the benefit of storage without necessarily merging code-bases.

**Comment by paultag** [comment]
:confetti_ball: that'd be awesome!

**Comment by xllora** [comment]
Thanks for reaching out @barakmich! Yes, BadWolf is mostly focused on the abstraction layer and reasoning. The memory implementation is just a excuse to validate the semantics and work of the it. I was not aware of Cayley and it seems you covered the miles that we are not going to be covering, so as you said, it looks like and everybody wins. 

I'll dig into Cayley soon to understand it a bit before making any suggestions, but the driver seems an easy start. Currently, I am spending the spare cycles I have to finish a working version of BQL in Go. I am finishing the part of the graph clauses (the most tricky one) when that is done, the other parts of BQL are pretty straight forward.

**Comment by barakmich** [comment]
@xllora Sure, sounds good. I was actually discussing more in-depth with a colleague how this might all fit together, and I think I understand the value proposition you're trying to validate. In fact, it fits into a more general pattern that I'd love to collaborate on.

Feel free to reach out by email or IRC, for a longer discussion than fits in a comment box :)

**Comment by xllora** [comment]
Will do.

**Comment by mrisher** [comment]
Very exciting. I love when open source actually works!

**Comment by danbri** [comment]
@barakmich thanks for raising this - I was about to ask just the same. Some kind of convergence here would be great.

**Comment by xllora** [comment]
I just sent an off-band note with some thoughts to @barakmich.

**Comment by xllora** [comment]
@barakmich and I met today and we discussed a plan moving forward. I am going to close this issue. The two initial issues follow up issues for we came up are:

https://github.com/google/badwolf/issues/9
https://github.com/google/badwolf/issues/10
