### ISSUE TITLE
Add literals, node, or predicate to the HAVING clause

### ISSUE THREAD

**Issue by xllora** [google/badwolf#56]
https://github.com/google/badwolf/blob/master/bql/grammar/grammar.go#L612

Does not contain any of the elements that form and object making the comparison bounded on flexibility.

**Comment by rogerlucena** [comment]
The final orientation for this Issue was:

> We shall not allow inequalities for **nodes** and **predicates** inside `HAVING` clauses, only equalities are allowed there for them (for clarity and to avoid confusion with regards to what is indeed being compared - the ID or the type of a node (or both)? the ID or the timestamp of a predicate? and so on). In the case of inequalities an error should be returned instructing the user to use the `ID`/`TYPE`/`AT` keywords and leverage the extracted bindings to do these comparisons in a clearer way. 
> 
> For **literals**, on the other hand, we support both equalities and inequalities inside `HAVING`.

To illustrate, taking the example of predicate inequalities inside `HAVING` clauses, the user shall be oriented to do something like:

```
SELECT ?s, ?p, ?o
FROM ?family
WHERE {
    ?s ?p ID ?pID AT ?time ?o
}
HAVING (?pID < "parent_of"^^type:text) AND (?time > 2016-03-01T00:00:00-08:00);
```

But, if the user wants to do just an equality they can do it directly as it does not cause any confusion:

```
SELECT ?s, ?p, ?o
FROM ?family
WHERE {
    ?s ?p ?o
}
HAVING ?p = "parent_of"@[];
```

The same applies for nodes.

**Comment by rogerlucena** [comment]
This Issue was finished with the PRs: #117, #134, #137, #138  

Previous work done on this Issue (mainly regarding node and literal comparisons): #102,  #100.
