### ISSUE TITLE
Long running instance

### ISSUE THREAD

**Issue by andreaferretti** [google/badwolf#63]
Excuse for the probably very naive question. I think I have a working badwolf instance, which I obtained by

```
go get golang.org/x/net/context
go get github.com/peterh/liner
go get github.com/google/badwolf/...
```

(is this the right way? It is not mentioned anywhere how to install).

In any case, I am able to use the `bw` tool and follow the examples, use `bw bql` to get a REPL and so on.

The question is: how do I leave a long running instance of badwolf? Even assuming I want to keep the data in RAM (persistence is not a priority right now, even though I see there are [persistent backends](https://github.com/xllora/bwdrivers) ) each time I run the `bw` an entire new instance of badwolf is created and apparently destroyed.

I assume there must be some way to leave badwolf running in the background and keep querying the existing graphs (even using the `bw` tool, preferably with some kind of driver/network interface) but I could not find any information on this

For instance, it is not clear to me how to use the `bw export` command: by the time I run a new `bw` process, everything in the previous runs is lost, hence there is nothing to export. Similarly, I can run `bw load`, but then data is lost as soon as the command returns. I am sure I am missing something obvious and fundamental here

**Comment by xllora** [comment]
There is a publicly available persistent backend you can get as you pointed out here

https://github.com/xllora/bwdrivers

Instead of getting the BW directly form here, go to that repo, follow the read me and build the new `bw` command line from there. You will get a ` bw` binary that will now have a `--driver` flag that supports, the traditional in `VOLATILE` model and the persistent one `BWBOLT` built using https://github.com/boltdb/bolt.

Once you have the new binary, you can just run this to make sure all the BoltDB flags required are available.

```
 $ ./bin/bw -h
Usage of ./bin/bw:
  -bolt_db_path string
        The path to the Bolt database to use.
  -bql_channel_size int
        Internal channel size to use on BQL queries.
  -driver string
        The storage driver to use {VOLATILE|BWBOLT}. (default "VOLATILE")
```

Please let me know if you have troubles following the instructions here

https://github.com/xllora/bwdrivers/blob/master/README.md

on how to build it.

**Comment by andreaferretti** [comment]
My problem is really not persistence, it is something quite ore basic.

Even using just memory, is there a way to  - I quite don't know how to phrase it - not shutdown the whole db after every query?

I tried to use the BOLT driver - no problems in building it, but I still was not able to

* write some data with `bw run -driver BWBOLT -bolt_db_path foo write.qbl`
* read back that data with a second command  `bw run -driver BWBOLT -bolt_db_path foo read.qbl`

**Comment by xllora** [comment]
Not sure I follow correctly, but you would like to have the driver connected for running all those query spread across two files right? Run was just written for running one file at a time

https://github.com/google/badwolf/blob/master/tools/vcli/bw/run/run.go

This could easily be extended to support running multiple files on the argument, instead. This should be pretty simple by modifying it around here

https://github.com/google/badwolf/blob/master/tools/vcli/bw/run/run.go#L58

**Comment by andreaferretti** [comment]
Not quite, that was just an example. Let me try to put it differently.

Say I want to use redis (mysql, postrgres, cassandra, whatever). I can start the server today, come back tomorrow and the server will still be running. I can then connect and store some data. Come back the day after and query that data.

What I am not finding is the command to start a server, without necessarily running queries.

Is seems that something *is* started when I run `bw`, but the process seems to exist only for the time that the queries are executed. As soon as `bw` returns, there is no server running anymore.

Is there a way to run badwolf, and then - separately - use the`bw` command line tool to run queries against it?

I hope the question is clear, I am trying my best, and I am probably missing something very, very basic

**Comment by xllora** [comment]
Got it now :D 

You cannot find it because there is no server implementation, yet. gRPC or some form of REST/SPARQL protocol service is on the future TODO list, but  first we want to finish the language constructs. Having that said, you could write a simple on that wraps the driver alive and calls the run BQL command. That should be pretty straight forwards.

**Comment by andreaferretti** [comment]
Ok, thank you, I thought I was missing something! :-)

At this stage, badwolf is not really suitable for my use case, but thank you nevertheless for the help!

**Comment by xllora** [comment]
Thanks for reaching out :)

**Comment by xllora** [comment]
@andreaferretti I just commit something that may help on what you were trying to do. Please see

https://github.com/google/badwolf/blob/master/docs/command_line_tool.md#command-server

**Comment by andreaferretti** [comment]
Thank you, it looks just like what I was trying to achieve! It would help to have a little example of the format in which queries are to be posted

**Comment by andreaferretti** [comment]
Another small thing: the JSON returned by the endpoint is not valid (apparently the query is not quoted correctly if it contains newlines)

**Comment by xllora** [comment]
I'll try to take a look soonish. I just put it together and there is not testing whatsoever :)

**Comment by xllora** [comment]
@andreaferretti I just pushed a6d888dbc00ddfc0129587a0e243515b5c4776de that contains a fix for the invalid JSON and removes some internal table representation data that was leaking. Could you take it for a spin and tell me if you run into other issues?

For instance you can pass this to the endpoint

```
create graph ?test;

insert data into ?test {
   /foo<id> "knows"@[] /bar<id>.
   /foo<id> "follows"@[] /bar<id>
};

select ?s,?p,?o,?k,?l,?m
from ?test
where {
  ?s ?p ?o.
  ?k ?l ?m
};
```

and you should get the following JSON on a newly started server

```
[{
	"query": "create graph ?test;",
	"msg": "[OK]",
	"table": {
		"bindings": [],
		"rows": []
	}
}, {
	"query": "insert data into ?test {     /foo<id> \"knows\"@[] /bar<id>.     /foo<id> \"follows\"@[] /bar<id>  };",
	"msg": "[OK]",
	"table": {
		"bindings": [],
		"rows": []
	}
}, {
	"query": "select ?s,?p,?o,?k,?l,?m  from ?test  where {    ?s ?p ?o.    ?k ?l ?m  };",
	"msg": "[OK]",
	"table": {
		"bindings": ["?s", "?p", "?o", "?k", "?l", "?m"],
		"rows": [{
			"?s": {
				"node": "/foo<id>"
			},
			"?p": {
				"pred": "\"knows\"@[]"
			},
			"?o": {
				"node": "/bar<id>"
			},
			"?k": {
				"node": "/foo<id>"
			},
			"?l": {
				"pred": "\"knows\"@[]"
			},
			"?m": {
				"node": "/bar<id>"
			}
		}, {
			"?s": {
				"node": "/foo<id>"
			},
			"?p": {
				"pred": "\"knows\"@[]"
			},
			"?o": {
				"node": "/bar<id>"
			},
			"?k": {
				"node": "/foo<id>"
			},
			"?l": {
				"pred": "\"follows\"@[]"
			},
			"?m": {
				"node": "/bar<id>"
			}
		}, {
			"?s": {
				"node": "/foo<id>"
			},
			"?p": {
				"pred": "\"follows\"@[]"
			},
			"?o": {
				"node": "/bar<id>"
			},
			"?k": {
				"node": "/foo<id>"
			},
			"?l": {
				"pred": "\"knows\"@[]"
			},
			"?m": {
				"node": "/bar<id>"
			}
		}, {
			"?s": {
				"node": "/foo<id>"
			},
			"?p": {
				"pred": "\"follows\"@[]"
			},
			"?o": {
				"node": "/bar<id>"
			},
			"?k": {
				"node": "/foo<id>"
			},
			"?l": {
				"pred": "\"follows\"@[]"
			},
			"?m": {
				"node": "/bar<id>"
			}
		}]
	}
}]
```

**Comment by xllora** [comment]
@andreaferretti also updated the documentation 

https://github.com/google/badwolf/blob/master/docs/command_line_tool.md#command-server

with a quick explanation.

**Comment by andreaferretti** [comment]
Thank you, now it's valid JSON in my small experiment!
