### ISSUE TITLE
Assert type covariance in query?

### ISSUE THREAD

**Issue by immesys** [google/badwolf#67]
How does one use type covariance in a query? The documentation doesn't cover it.

**Comment by xllora** [comment]
Hi @immesys could you share a quick example to make that I can use to answer?

**Comment by immesys** [comment]
Well say I have 
/foo/bar<baz> "pred"@[] /obj<0>

and now I want to use the fact that /foo covariant /foo/bar in some way. Is the documentation implying this is an out-of-band convention or is there some way of using it in a query?

**Comment by xllora** [comment]
Yes, correct, right now there is no support for those operation in BQL. We plan to introduce filter functions first on the where clauses. When we have that in place, we will be able to add a few different ops. 

Having that said, if you are manipulating nodes directly

https://github.com/google/badwolf/blob/9b79adc583ab3911c3f75ad1fecd5d8f976f2f31/triple/node/node.go#L40

Implements the functionality.

**Comment by immesys** [comment]
thanks
