### ISSUE TITLE
Ability to retract a triple or set an "unanchor" time

### ISSUE THREAD

**Issue by bruth** [google/badwolf#8]
A triple is asserted with an anchor time, but there is no mechanism for *unanchoring* the triple, that is invalidating the triple. One approach I thought about was have a `nil` type that denotes the triple has been retracted. Another method could be to implement this in the logic of the storage layer. When a triple is "deleted", the triple is stored in a retracted set. When triples are requested, matched triples would need to be evaluated against the retracted set before being returned. Have you thought about this at all?

**Comment by xllora** [comment]
Tough question. 

Anchored triples are only valid on that time anchor or in a range that includes that range. Moving the range outside the anchor nullifies the triple. For instance, imagine you have a triple anchored on 7 different spots

past |----x------x---x------x---x---| now |----x---x---| future

So they are valid depending on your query. For instance [ ] below indicate your query range

past |----x----[--x---x--]----x---x---| now |----x---x---| future => 2 valid, 5 "inactive"

past |----x------x---x------x---x---| now |--[--x---x---| future => 2 valid, 5 "inactive"

past |----x------x---x------x-]--x---| now |----x---x---| future => 4 valid, 3 "inactive"

Where the "inactive" once are never going to be surfaced in the query.

For the corner cases you need to get rid of and anchored value, the way we have been dealing with those so far has been actually removing the anchored triple that needs to be remove (see the remove triple capabilities). This is permanent. The downside is you loose the record of their existence ever. However, this have been working well as long as you do not need to do massive deletes. The reasone is the query control on the time range to "validate" triples. 

Also, to balancing storage pressure another useful strategy is to expire and delete triples by anchor. For instance, imagine you add the triple every day/hour (or some arbitrary regular time, e.g. events up to then) invalidating them after a given horizon (e.g. 15 days) works pretty well if you are focusing on time series. The other option is to remove those time ranges out of the query.

**Comment by bruth** [comment]
Thanks for the response. My use case is essentially storing entities and state changes over time and their related provenance information. I suppose one method would be to assert a fact with an encoded "nil" value such as an empty byte slice or one containing a "magic" byte which to flag it as a retracted triple. The `storage.Graph` methods could implicitly filter those triples out.

**Comment by bruth** [comment]
Would you consider adding a "nil" data type with explicit semantics of it being unset and therefore not included in the result set? For example:

```
// They were in love..
/people<Joe>    "married_to"@[]    /people<Mary>

// One year later..
/people<Joe>    "married_to"@[]    ""^^type:nil
```

**Comment by bruth** [comment]
Or use a special literal value:

```
/people<Joe>    "married_to"@[]    /_nil

**Comment by xllora** [comment]
The issue with adding ```nil``` the way you expressed is that you end in a weird place. For instance:

```
// They were friends.
/people<Joe>    "friend_to"@[]    /people<Mary>
/people<Joe>    "friend_to"@[]    /people<Anne>
/people<Joe>    "friend_to"@[]    /people<Peter>
/people<Joe>    "friend_to"@[]    /people<Amy>

// One year later..
/people<Joe>    "friend_to"@[]    ""^^type:nil
```

What does it mean. Joe does not have any friend anymore? Usually for this cases you would run with [Reification](https://github.com/google/badwolf/blob/4bfc91b37f9304b08ed01bd0433685a0b5f36ac3/docs/temporal_graph_modeling.md#blank-nodes-and-triple-reification) since what you are actually after is predicating a fact over another fact.

```
// They were friends original triples.
/people<Joe>    "friend_to"@[]    /people<Mary>
/people<Joe>    "friend_to"@[]    /people<Anne>
/people<Joe>    "friend_to"@[]    /people<Peter>
/people<Joe>    "friend_to"@[]    /people<Amy>

// Reification with fact predication.
/people<Joe>  "friend_to"@[]    /people<Mary>
/_<BUID> "_subject"@[] /people<Joe>
/_<BUID> "_predicate"@[] "friend_to"@[]
/_<BUID> "_object"@[] /people<Mary>

/people<Joe>    "friend_to"@[]    /people<Anne>
/_<BUID> "_subject"@[] /people<Joe>
/_<BUID> "_predicate"@[] "friend_to"@[]
/_<BUID> "_object"@[] /people<Anne>

...
```

Now if you want to say that Joe and Mary are note friends any more you could a a "valid" predicate to the reified statement. 

```
// They were friends original triples.
/people<Joe>    "friend_to"@[]    /people<Mary>
/people<Joe>    "friend_to"@[]    /people<Anne>
/people<Joe>    "friend_to"@[]    /people<Peter>
/people<Joe>    "friend_to"@[]    /people<Amy>

// Reification with fact predication.
/people<Joe>  "friend_to"@[]    /people<Mary>
/_<BUID> "_subject"@[] /people<Joe>
/_<BUID> "_predicate"@[] "friend_to"@[]
/_<BUID> "_object"@[] /people<Mary>
/_<BUID> "valid"@[] "false"^^type:bool

/people<Joe>    "friend_to"@[]    /people<Anne>
/_<BUID> "_subject"@[] /people<Joe>
/_<BUID> "_predicate"@[] "friend_to"@[]
/_<BUID> "_object"@[] /people<Anne>
/_<BUID> "valid"@[] "true"^^type:bool

...
```

Being now able to invalidate individual predicates. Hence, when you query now write query to get currents friends of Joe, you would write something along the lines of

```
SELECT ?fs
FROM ?some_graph
WHERE {
  ?bn "_subject"@[] /people<Joe>
  ?bn "_predicate"@[] "friend_to"@[]
  ?bn "_object"@[] ?fs
  ?bn "valid"@[] "true"^^type:bool
};
```

Or to find the ones they are not friend of via

```
SELECT ?fs
FROM ?some_graph
WHERE {
  ?bn "_subject"@[] /people<Joe>
  ?bn "_predicate"@[] "friend_to"@[]
  ?bn "_object"@[] ?fs
  ?bn "valid"@[] "false"^^type:bool
};
```

The are some nuisance on updating the ```value``` predicate since you would like to anchor it in time instead, but that would be the idea to do what you wanted. 

However, as I said, unless you need to keep that data around for some reason, the easier way is to just delete the triple

```
/people<Joe>  "friend_to"@[]    /people<Mary>
```

:D

**Comment by bruth** [comment]
You beat me to it! I was writing out the same reification process. I definitely different think about the implication of setting the predication to `nil` when multiple objects are associated. Thank you for the thoughts and explanation.
