### ISSUE TITLE
CONTRIBUTING guide has typo/extra text

### ISSUE THREAD

**Issue by mbrukman** [google/badwolf#80]
The [`CONTRIBUTING.md` file](https://github.com/google/badwolf/blob/e54ec6d744a55d7f43eba31c8d09ade1e8515342/CONTRIBUTING.md) has a cryptic sentence at the end:

> This commit can be part of your first [Differential][] code review.

This appears to be missing a link and out-of-context. What's "Differential"? Is it a [component of Phabricator](https://secure.phabricator.com/book/phabricator/article/differential/)? But then how does it relate to GitHub PRs which is presumably the way to contribute to this project?

Either there should be a link there to explain where Differential comes in, or this sentence should be removed entirely.

**Comment by xllora** [comment]
Thx. Updated the file accordingly.
