### ISSUE TITLE
Questions: EAV vs Triplestore, Gremlin, Geographical data, immutability, further readings?

### ISSUE THREAD

**Issue by amirouche** [google/badwolf#82]
Héllo,

First and foremost thanks for sharing this project! This is very interesting!

# Me, Myself and I

I am a database modeling enthusiast, I created a database in Python called AjguDB, which is a graphdb on top EAV (on top of wiredtiger ordered key value store, it's similar to boltdb). I did a similar project in Scheme which is can be queried using miniKanren (a logic language embedded in Scheme language). My inspiration is mostly datomic database even if I skipped the immutable part.

# EAV vs Triplestores

I used to think that EAV was a triplestore.I am reconsidering that fact. It seems like EAV model is less generic that triplestore model. My understanding, is that both are good at modeling sparse matrix / multidimentional data but EAV is really good at representing documents whereas triplestores are good at representing triples (or facts). One might say, that a document is a set of triples. But in EAV model you don't have control over the entity, it's randomly generated. At the end of the day, I think triplestore is just EAV with E that is not a unique identifier. WDYT?

# Gremlin querying

Is it possible to adapt Gremlin to work on quads?

# Geographical data

I am surprised that there is no mention of geographical data in some way. Is it something you plan to add?

# Immutability

How do you cope with immutability during querying? Here is a pratical example, say there is triple that says that «there is hundred people in a twon in 2017». Now, it's 2018, do I need to create a new triple or update the old triple? Do triples have an history? It seems to me that a database present in BadWolf must be clean, you can not fix typos or it will kludge results.

# Further readings

Can you recommend me stuff to read about BadWolf. 

I will dive into boltdb drivers.

**Comment by xllora** [comment]
Hi @amirouche,

I am a bit confused about your EVT question. Would you mind rephrasing what you mean by it?

About, gremlin I do not see why not (you may have to model time as an edge property IIRC).

There is no mention about modeling geographical data, since you can model it directly. However, querying may just be bounded by bounding boxes. If you want more elaborated query mechanics, all proposals are welcome! We will add them to the list of things to evaluate/prioritize.

Immutability, Yes, predicates are anchored in time, so you will create one for 2018 and is up to you then on the query to decide which range you want to consider. You may want to check the doc folder for examples.

Further reading, please see the doc folder.

**Comment by amirouche** [comment]
I read about sparql and rdf throught [zehefyu93](https://github.com/amirouche/neon/).
Here is the tag line:

> The main use case is to be the *git of data*. 

More like this.

> That is, use  zehefyu93 to
> store structured or semi-structured data that can be bigger than RAM.
> And enable the same cooperative practices that you see in software
> development around data. The goal is to foster *reproducible science*.

**Comment by amirouche** [comment]
> I am a bit confused about your EVT question. Would you mind rephrasing what you mean by it?

Entity - Value - Time

In zehefyu93, it stores WGSPOTxSD: Weed, Graph, Subject Predicate, Object, Transaction, SoftDelete. I came to this tuple because in the case of EAV since Entities are random, you can not share sync two different database. In a triple store the equivalent of the `entity` is `weed` it set by the user of database. The Weed identifier is only used internally for making each end user tuple unique. End user tuple look like the following:

> (Graph, Subject, Predicate, Object)

The remaining terms in the stored tuple ie. Transaction (Tx) and SoftDelete (SD) are manipulated respectively by a `git`-like API. SD basically means that the tuple doesn't exist until it's re-`add`'ed later by the end user.

**Comment by amirouche** [comment]
> There is no mention about modeling geographical data, since you can model it directly. However, 
> querying may just be bounded by bounding boxes. If you want more elaborated query mechanics, all 
> proposals are welcome! We will add them to the list of things to evaluate/prioritize.

I studied a bit space feeling curves. I think the best intro is at [amazon](https://forums.foundationdb.org/t/data-modeling-efficient-encoding-for-wgs84-coordinate-key-ids/354/8).

IIRC, if I store bytes in in graph, subject, predicate, object are bytes, I can take advantage of it to store small timeseries. I guess.

**Comment by amirouche** [comment]
> Immutability, Yes, predicates are anchored in time, so you will create one for 2018 and is up to you then on the query to decide which range you want to consider. You may want to check the doc folder for examples.

In my project, one use git like workflow. You must checkout a `branch` of the `history` to be able to query it and add `quad` or soft-kill them.

**Comment by amirouche** [comment]
I wrote [my version paper](https://github.com/amirouche/zehefyu93/blob/master/doc/MOCHA2018/preview/neon-mocha-2018-preview.pdf)!

**Comment by xllora** [comment]
Hi! Wow, lots of stuff here. Glad you got the you first paper out! Starting is usually the hardest part :)
