### ISSUE TITLE
TestPartialUUID fails on Windows

### ISSUE THREAD

**Issue by MichaelRoeder** [google/badwolf#84]
## Problem

`TestPartialUUID` of `predicate_test.go` fails on some Windows machines with the following error message:
```
--- FAIL: TestPartialUUID (0.00s)
        predicate_test.go:161: predicates "foo"@[2018-07-02T22:27:47.3944176+02:
00] and "foo"@[2018-07-02T22:27:47.3944176+02:00] should have different UUID; go
t "4c812f28-2601-5f0f-8730-092580e0cd62"="4c812f28-2601-5f0f-8730-092580e0cd62"
```

## Cause

The problem is caused by the test itself. It creates two `Predicate` instances with
```golang
	p1, err := NewTemporal("foo", time.Now())
	if err != nil {
		t.Fatal(err)
	}
	p2, err := NewTemporal("foo", time.Now())
```
assuming that `time.Now()` will generate two different timestamps. However, this does not seem to be the case on Windows machines as it can be seen in the error message above in which both timestamps are exactly the same. (I didn't found an official source to validate whether there is an issue regarding nano seconds of timestamps but I tested it on two different machines of two different developers with Windows 7 and 10. Both showed the same issue).

## Solution

Fix the creation of the second predicate by making sure that the timestamp is increased by at least 1 nanosecond:
```golang
	p2, err := NewTemporal("foo", time.Now().Add(time.Duration(1)))
```
I didn't created a PR for that because signing this Google CLA as described in the [contributing guidelines] seems to much overhead for such an easy fix :wink: 
However, feel free to use the solution above (or whatever solution you prefer) to fix the wrong test.

Thanks :smile:

**Comment by xllora** [comment]
@MichaelRoeder thanks so much for the nice report that also includes the solution. Mmh, we may have to dig some Win machine to run the tests :) I am just pushing the fix you proposed. Please let me know if you run into any other weirdness on Windows.

**Comment by MichaelRoeder** [comment]
I tested your commit and it worked for me. Thanks for your fast response :)

**Comment by xllora** [comment]
Thanks for spending the time looking into it and even providing a solution for it!
